### ISSUE TITLE
Some more resources

### ISSUE THREAD

**Issue by balupton** [reignite/burnout.io#17]
- http://nodeup.com/eighty / https://github.com/nodeup/contribute/issues/49 - added in #21 (more resources in the website page)
- http://baugues.com/depression - added in #20 
- https://github.com/cascadiajs/2015.cascadiajs.com/issues/228
- https://github.com/berlinphp/berlinphp.github.com/pull/78
- https://github.com/dopodcast/dopodcast.github.io/issues/12 (plenty more resources in the comments)
  - Developers & Depression: http://blog.baugues.com/speaking
  - Open Sourcing Mental Illness: http://funkatron.com/osmi.html
  - Frustration Driven Development: http://www.youtube.com/watch?v=1BYZCC5khjE
  - Stanford's Sapolsky On Depression in U.S. (Full Lecture) http://www.youtube.com/watch?v=NOAgplgTxfc
- https://github.com/jsfest/oakland-cfp/issues/31
- https://github.com/dmanners/avoiding-burnout
- https://medium.com/@balupton/surviving-free-culture-f99b39ceb059 - added in #19

**Comment by bemosior** [comment]
Many thanks! I will definitely add these as I find time.

**Comment by bemosior** [comment]
- [ ] http://nodeup.com/eighty / nodeup/contribute#49 - added in #21 (more resources in the website page)
- [ ] http://baugues.com/depression - added in #20
- [ ] cascadiajs/2015.cascadiajs.com#228
- [ ] berlinphp/berlinphp.github.com#78
- [ ] dopodcast/dopodcast.github.io#12 (plenty more resources in the comments)
- [ ] Developers & Depression: http://blog.baugues.com/speaking
- [ ] Open Sourcing Mental Illness: http://funkatron.com/osmi.html
- [ ] Frustration Driven Development: http://www.youtube.com/watch?v=1BYZCC5khjE
- [ ] Stanford's Sapolsky On Depression in U.S. (Full Lecture) http://www.youtube.com/watch?v=NOAgplgTxfc
- [ ] jsfest/2014-oakland-cfp#31
- [ ] https://github.com/dmanners/avoiding-burnout
- [ ] https://medium.com/@balupton/surviving-free-culture-f99b39ceb059 - added in #19

**Comment by AaronSachs** [comment]
Adding the rest of this in a forthcoming commit.
